#MAKEFILE
# name of compiler: wdjc
# name of file extension: .dj

# FILES NEEDED

# TESTS = \
# ....


OBJS = scanner.cmo parser.cmo ast.cmo sast.cmo semcheck.cmo compile.cmo  wdjc.cmo 

wdjc : $(OBJS)
	ocamlc -o wdjc $(OBJS)


.PHONY : test
test : wdjc testall.sh
	./testall.sh


scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

.PHONY :	 clean
clean :
	rm -f wdjc parser.ml parser.mli scanner.ml testall.log \
	*.cmo *.cmi *.out *.diff

# Generated by ocamldep *.ml *.mli
ast.cmo: 
ast.cmx:
sast.cmo:
sast.cmx:
semcheck.cmo: ast.cmi sast.cmi
semcheck.cmx: ast.cmx sast.cmx
parser.cmo: ast.cmo parser.cmi 
parser.cmx: ast.cmx parser.cmi 
parser.cmi: ast.cmo 
scanner.cmo: parser.cmi 
scanner.cmx: parser.cmx 

compile.cmo: ast.cmo 
compile.cmx: ast.cmx 

wdjc.cmo: scanner.cmo parser.cmi ast.cmo sast.cmo semcheck.cmo compile.cmo 
wdjc.cmx: scanner.cmx parser.cmx ast.cmx sast.cmx semcheck.cmx compile.cmx







 
